

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/student-manager?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: newpass

mybatis:
  config-location: classpath:mybatis-configuration.xml
  mapper-locations: classpath:mapper/*.xml

